@startuml

+class Cliente <<Serializable>> {
    -id: Long
    -nombre: String
    -apellido: String
    -email: String
    -createAt: Date
    -facturas: List<Factura>
    .. Getter ..
    .. Setter ..
}

+class Factura <<Serializable>> {
    -- private data --
    -id: Long
    -folio: Integer
    -descripcion: String
    -observacion: String
    -fecha: Date
    -cliente: Cliente
    -- public methods --
    +calcularTotal(): Long
    .. Getter ..
    .. Setter ..
}

+class ItemFactura <<Serializable>> {
    -- private data --
    -id: Long
    -cantidad: Integer
    -- public methods --
    +calcularImporte(): Double
    .. Getter ..
    .. Setter ..
}

+class Producto <<Serializable>> {
    -nombre: String
    -precio: Long
    .. Getter ..
    .. Setter ..
}

Cliente o-- Factura
Factura *-- ItemFactura
ItemFactura --> Producto

@enduml
